### ISSUE TITLE
Add compatbility for Binscure Obfuscator (Feature Request)

### ISSUE THREAD

**Issue by JohnShiozo** [GraxCode/threadtear#39]
idk if this the right format of Issue but ill try
Could you add Compatbility to Binscure Obfuscator
heres the website link https://binclub.dev/binscure/

**Comment by Col-E** [comment]
1. Attaching samples to work off of is always a plus

2. The problem is binscure manipulates the class to not be parsable by ASM, which is what Threadtear is based on.

I have a basic patching routine in my tool, [Recaf](https://github.com/Col-E/Recaf), that happens whenever you load a binscure jar/class. You can export the jar and run further deobfuscation in ThreadTear afterwards.

**Comment by x4e** [comment]
invalid issue

**Comment by ItzRiotz** [comment]
$$$ clapped by binscure $$$
